from .swap import SwapTab
from .add_liquidity import AddLiquidityTab
from .remove_liquidity import RemoveLiquidityTab
from .supply import SupplyLendingTab
from .withdraw import WithdrawLendingTab
from .stark_id import StarkIdMintTab
from .dmail import DmailSendMailTab
from .deploy import DeployTab
from .upgrade import UpgradeTab
from .transfer import TransferTab
from .bridge import BridgeTab
