from .base import TaskBase
from .base.add_liquidity import AddLiquidityTaskBase
from .base.remove_liquidity import RemoveLiquidityTaskBase
from .base.supply import SupplyTaskBase
from .base.swap import SwapTaskBase
from .base.withdraw import WithdrawTaskBase
from .base.bridge import BridgeTaskBase

from .avnu import AvnuSwapTask
from .deploy import DeployTask
from .deploy import UpgradeTask
from .dmail import DmailSendMailTask
from .identity import IdentityMintTask
from .jediswap import JediSwapTask
from .jediswap import JediSwapAddLiquidityTask
from .jediswap import JediSwapRemoveLiquidityTask
from .k10swap import K10SwapTask
from .k10swap import K10SwapAddLiquidityTask
from .k10swap import K10SwapRemoveLiquidityTask
from .myswap import MySwapTask
from .myswap import MySwapAddLiquidityTask
from .myswap import MySwapRemoveLiquidityTask
from .sithswap import SithSwapTask
from .sithswap import SithSwapAddLiquidityTask
from .sithswap import SithSwapRemoveLiquidityTask
from .test import TestTask
from .zklend import ZkLendSupplyTask
from .zklend import ZkLendWithdrawTask
from .fibrous import FibrousSwapTask
from .orbiter import OrbiterBridgeTask
from .stark_bridge import StarkBridgeTask
from .transfer import TransferTask
from .starkverse import StarkVersePublicMintTask
from .starkex import StarkExSwapTask
from .starkex import StarkExAddLiquidityTask
from .starkex import StarkExRemoveLiquidityTask
from .unframed import UnframedCancelOrdersTask
from .flex import FlexCancelOrdersTask
from .zerius import ZeriusMintTask

from .random_task.swap import RandomSwapTask
from .random_task.liquidity import RandomAddLiquidityTask

from .virtual_task.avnu import AvnuSwapVirtualTask
from .virtual_task.deploy import DeployVirtualTask
from .virtual_task.deploy import UpgradeVirtualTask
from .virtual_task.dmail import DmailSendMailVirtualTask
from .virtual_task.identity import IdentityMintVirtualTask
from .virtual_task.jediswap import JediSwapVirtualTask
from .virtual_task.jediswap import JediSwapAddLiquidityVirtualTask
from .virtual_task.jediswap import JediSwapRemoveLiquidityVirtualTask
from .virtual_task.k10swap import K10SwapVirtualTask
from .virtual_task.k10swap import K10SwapAddLiquidityVirtualTask
from .virtual_task.k10swap import K10SwapRemoveLiquidityVirtualTask
from .virtual_task.myswap import MySwapVirtualTask
from .virtual_task.myswap import MySwapAddLiquidityVirtualTask
from .virtual_task.myswap import MySwapRemoveLiquidityVirtualTask
from .virtual_task.sithswap import SithSwapVirtualTask
from .virtual_task.sithswap import SithSwapAddLiquidityVirtualTask
from .virtual_task.sithswap import SithSwapRemoveLiquidityVirtualTask
from .virtual_task.test import TestVirtualTask
from .virtual_task.zklend import ZkLendSupplyVirtualTask
from .virtual_task.zklend import ZkLendWithdrawVirtualTask
from .virtual_task.fibrous import FibrousSwapVirtualTask
from .virtual_task.orbiter import OrbiterBridgeVirtualTask
from .virtual_task.stark_bridge import StarkBridgeVirtualTask
from .virtual_task.transfer import TransferVirtualTask
from .virtual_task.starkverse import StarkVersePublicMintVirtualTask
from .virtual_task.starkex import StarkExSwapVirtualTask
from .virtual_task.starkex import StarkExAddLiquidityVirtualTask
from .virtual_task.starkex import StarkExRemoveLiquidityVirtualTask
from .virtual_task.unframed import UnframedCancelOrdersVirtualTask
from .virtual_task.flex import FlexCancelOrdersVirtualTask
from .virtual_task.zerius import ZeriusMintVirtualTask
