from .base import TaskBase
from .base.add_liquidity import AddLiquidityTaskBase
from .base.remove_liquidity import RemoveLiquidityTaskBase
from .base.supply import SupplyTaskBase
from .base.swap import SwapTaskBase
from .base.withdraw import WithdrawTaskBase

from .avnu import AvnuSwapTask
from .deploy import DeployTask
from .dmail import DmailSendMailTask
from .identity import IdentityMintTask
from .jediswap import JediSwapTask
from .jediswap import JediSwapAddLiquidityTask
from .jediswap import JediSwapRemoveLiquidityTask
from .k10swap import K10SwapTask
from .myswap import MySwapTask
from .myswap import MySwapAddLiquidityTask
from .myswap import MySwapRemoveLiquidityTask
from .sithswap import SithSwapTask
from .sithswap import SithSwapAddLiquidityTask
from .sithswap import SithSwapRemoveLiquidityTask
from .test import TestTask
from .zklend import ZkLendSupplyTask
from .zklend import ZkLendWithdrawTask
from .fibrous import FibrousSwapTask
from .orbiter import OrbiterBridgeTask
from .stark_bridge import StarkBridgeTask

from .random_task.swap import RandomSwapTask
from .random_task.liquidity import RandomAddLiquidityTask